### ISSUE TITLE
Have you considered using backends other than Z3? 

### ISSUE THREAD

**Issue by wujingyue** [nunoplopes/alive#17]
Z3 has a relatively restricted license, which prevents companies from using it for commercial purposes. I wonder if you have considered or estimated how difficult it is to add other backends such as STP.

**Comment by nunoplopes** [comment]
For some optimizations we generate quantified bit-vector formulas. Therefore, STP is not currently an option (otherwise we would have to handle the quantifiers ourselves).
Adding support for multiple solvers is desirable since it then allows one to cross-check results and to benchmark different solvers.
