### ISSUE TITLE
apparent infinite loop

### ISSUE THREAD

**Issue by regehr** [nunoplopes/alive#43]
this hangs overnight, but with Python using 100% of a CPU, not Z3

```
----------------------------------------
Optimization: 1
Precondition: true
  %1 = urem i32 %0, 679
  %out = icmp eq 0, %1
=>
  %3a = mul %0, 2068415767
  %out = icmp ult %3a, 6325431
```

**Comment by regehr** [comment]
(using the newsema branch)

**Comment by nunoplopes** [comment]
since we use Z3 as a library, it shows up under the python process. I checked this example and it gets stuck in the SAT solver. Alive2 somehow manages to do this one much faster (it's using a different tactic).
So there's not much to do here. I'll refrain from doing optimizations in Alive, expecting Alive2 to fully replace Alive in a few months from now :)
